# Generated by Django 3.2.16 on 2022-12-08 04:45

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("esp_name", models.CharField(editable=False, max_length=256)),
                (
                    "message_id",
                    models.CharField(editable=False, max_length=256, null=True),
                ),
                ("subject", models.CharField(editable=False, max_length=998)),
                ("content", models.TextField(editable=False, null=True)),
                ("content_html", models.TextField(editable=False, null=True)),
                ("status", models.CharField(editable=False, max_length=256)),
                ("recipient_email", models.EmailField(editable=False, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="MessageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(editable=False)),
                ("event_name", models.CharField(editable=False, max_length=32)),
                ("payload", models.JSONField(default=dict, editable=False)),
                (
                    "sent_message",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_events",
                        to="anymail_history.sentmessage",
                    ),
                ),
            ],
        ),
    ]
