# Generated by Django 3.2.16 on 2022-12-08 04:45

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anymail_history", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sentmessage",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="MessageEvent",
            index=models.Index(
                fields=["created_on"], name="anymail_his_created_01395c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="MessageEvent",
            index=models.Index(
                fields=["event_name"], name="anymail_his_event_n_e3a465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentmessage",
            index=models.Index(
                fields=["created_on"], name="anymail_his_created_22d036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentmessage",
            index=models.Index(
                fields=["message_id"], name="anymail_his_message_1731a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentmessage",
            index=models.Index(
                fields=["recipient_email"], name="anymail_his_recipie_b46581_idx"
            ),
        ),
    ]
