name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: poetry install

      - name: Run tests
        run: poetry run coverage run -m pytest --cov=anymail_history --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
